name: rc
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=hc0c2ac7_1001
  - jpeg=9c=hfa6e2cd_1001
  - libffi=3.2.1=h6538335_1006
  - openjpeg=2.3.1=ha922770_0
  - openssl=1.1.1g=he774522_0
  - poppler=0.76.0=h92819f6_0
  - poppler-data=0.4.9=1
  - python_abi=3.6=1_cp36m
  - pyts=0.11.0=pyh9f0ad1d_0
  - alabaster=0.7.10=py36hcd07829_0
  - anaconda-client=1.6.14=py36_0
  - anaconda=custom=py36h363777c_0
  - anaconda-project=0.8.2=py36hfad2e28_0
  - asn1crypto=0.24.0=py36_0
  - astroid=1.6.3=py36_0
  - astropy=3.0.2=py36h452e1ab_1
  - attrs=18.1.0=py36_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py36h81696a8_1
  - backports.shutil_get_terminal_size=1.0.0=py36h79ab834_2
  - beautifulsoup4=4.6.0=py36hd4cc5e8_1
  - bitarray=0.8.1=py36hfa6e2cd_1
  - bkcharts=0.2=py36h7e685f7_0
  - blas=1.0=mkl
  - blaze=0.11.3=py36h8a29ca5_0
  - bleach=2.1.3=py36_0
  - blosc=1.14.3=he51fdeb_0
  - bokeh=0.12.16=py36_0
  - boto=2.48.0=py36h1a776d2_1
  - bottleneck=1.2.1=py36hd119dfa_0
  - bzip2=1.0.6=hfa6e2cd_5
  - cffi=1.11.5=py36h945400d_0
  - chardet=3.0.4=py36h420ce6e_1
  - click=6.7=py36hec8c647_0
  - cloudpickle=0.5.3=py36_0
  - clyent=1.2.2=py36hb10d595_1
  - colorama=0.3.9=py36h029ae33_0
  - comtypes=1.1.4=py36_0
  - console_shortcut=0.1.1=h6bb2dd7_3
  - contextlib2=0.5.5=py36he5d52c0_0
  - cryptography=2.6.1=py36h7a1dbc1_0
  - curl=7.64.1=h2a8f88b_0
  - cycler=0.10.0=py36h009560c_0
  - cython=0.28.2=py36hfa6e2cd_0
  - cytoolz=0.9.0.1=py36hfa6e2cd_0
  - dask=0.17.5=py36_0
  - dask-core=0.17.5=py36_0
  - datashape=0.5.4=py36h5770b85_0
  - decorator=4.3.0=py36_0
  - distributed=1.21.8=py36_0
  - docutils=0.14=py36h6012d8f_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - et_xmlfile=1.0.1=py36h3d2d736_0
  - expat=2.2.5=he025d50_0
  - fastcache=1.0.2=py36hfa6e2cd_2
  - filelock=3.0.4=py36_0
  - flask=1.0.2=py36_1
  - flask-cors=3.0.4=py36_0
  - freetype=2.9.1=ha9979f8_1
  - future=0.17.1=py36_0
  - get_terminal_size=1.0.0=h38e98db_0
  - gevent=1.3.0=py36hfa6e2cd_0
  - glob2=0.6=py36hdf76b57_0
  - greenlet=0.4.13=py36hfa6e2cd_0
  - h5py=2.7.1=py36h3bdd7fb_2
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.2=hac2f561_1
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36h047fa9f_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.6=py36h148d497_1
  - imageio=2.3.0=py36_0
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.2.1=py36_0
  - isort=4.3.4=py36_0
  - itsdangerous=0.24=py36hb6c5a24_1
  - jdcal=1.4=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36h292fed1_0
  - jsoncpp=1.8.4=h74a9793_0
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36h6d89b47_1
  - jupyter_core=4.4.0=py36h56e9d50_0
  - jupyterlab=0.32.1=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - keyring=18.0.0=py36_0
  - kiwisolver=1.0.1=py36h12c3424_0
  - krb5=1.16.1=hc04afaa_7
  - lazy-object-proxy=1.3.1=py36hd1c21d2_0
  - libcurl=7.64.1=h2a8f88b_0
  - libiconv=1.15=h1df5818_7
  - libnetcdf=4.6.1=h62daf8c_0
  - libpng=1.6.35=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.0.9=hb8ad9f9_1
  - libxml2=2.9.8=hadb2253_1
  - libxslt=1.1.32=hf6f1972_0
  - llvmlite=0.23.1=py36hcacf6c6_0
  - locket=0.2.0=py36hfed976d_1
  - lxml=4.2.1=py36heafd4d3_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py36h0e26971_1
  - matplotlib=3.0.1=py36hc8f65d3_0
  - mccabe=0.6.1=py36hb41005a_1
  - menuinst=1.4.14=py36hfa6e2cd_0
  - mistune=0.8.3=py36hfa6e2cd_1
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h57e144c_4
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h9258bd6_0
  - more-itertools=4.1.0=py36_0
  - mpmath=1.0.0=py36hacc8adf_2
  - msgpack-python=0.5.6=py36he980bc4_0
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.5.0=py36_0
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - networkx=2.1=py36_0
  - nltk=3.3.0=py36_0
  - nose=1.3.7=py36h1c3779e_2
  - notebook=5.5.0=py36_0
  - numba=0.38.0=py36h830ac7b_0
  - numexpr=2.6.5=py36hcd2f87e_0
  - numpy=1.15.4=py36ha559c80_0
  - numpy-base=1.15.4=py36h8128ebf_0
  - numpydoc=0.8.0=py36_0
  - odo=0.5.1=py36h7560279_0
  - olefile=0.45.1=py36_0
  - openpyxl=2.5.3=py36_0
  - packaging=17.1=py36_0
  - pandas=0.23.0=py36h830ac7b_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.2.0=py36_0
  - partd=0.3.8=py36hc8e763b_0
  - path.py=11.0.1=py36_0
  - pathlib2=2.3.2=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.43=ha925a31_0
  - pep8=1.7.1=py36_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pillow=5.2.0=py36h08bbbbd_0
  - pip=18.1=py36_0
  - pkginfo=1.4.2=py36_1
  - pluggy=0.6.0=py36hc7daf1e_0
  - ply=3.11=py36_0
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - psutil=5.4.5=py36hfa6e2cd_0
  - py=1.5.3=py36_0
  - pycodestyle=2.4.0=py36_0
  - pycosat=0.6.3=py36h413d8a4_0
  - pycparser=2.18=py36hd053e01_1
  - pycrypto=2.6.1=py36hfa6e2cd_8
  - pycurl=7.43.0.2=py36h7a1dbc1_0
  - pyface=6.0.0=py36_0
  - pyflakes=1.6.0=py36h0b975d6_0
  - pygments=2.2.0=py36hb010967_0
  - pylint=1.8.4=py36_0
  - pyodbc=4.0.23=py36h6538335_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36h785a196_1
  - pyqt=5.9.2=py36h6538335_2
  - pysocks=1.6.8=py36_0
  - pytables=3.4.3=py36he6f6034_1
  - pytest=3.5.1=py36_0
  - pytest-arraydiff=0.2=py36_0
  - pytest-astropy=0.3.0=py36_0
  - pytest-doctestplus=0.1.3=py36_0
  - pytest-openfiles=0.3.0=py36_0
  - pytest-remotedata=0.2.1=py36_0
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - pywavelets=0.5.2=py36hc649158_0
  - pywin32=223=py36hfa6e2cd_1
  - pywinpty=0.5.1=py36_0
  - pyyaml=3.12=py36h1d1928f_1
  - pyzmq=17.0.0=py36hfa6e2cd_1
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.5.7=py36_1
  - qtconsole=4.3.1=py36h99a29a9_0
  - qtpy=1.8.0=py_0
  - requests=2.18.4=py36h4371aae_1
  - rope=0.10.7=py36had63a69_0
  - ruamel_yaml=0.15.35=py36hfa6e2cd_1
  - scikit-image=0.13.1=py36hfa6e2cd_1
  - scikit-learn=0.19.1=py36h53aea1b_0
  - scipy=1.1.0=py36h4f6bf74_1
  - seaborn=0.8.1=py36h9b69545_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36h17d0c80_0
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36h4db2310_1
  - snappy=1.1.7=h777316e_3
  - snowballstemmer=1.2.1=py36h763602f_0
  - sortedcollections=0.6.1=py36_0
  - sortedcontainers=1.5.10=py36_0
  - sphinx=1.7.4=py36_0
  - sphinxcontrib=1.0=py36hbbac3d2_1
  - sphinxcontrib-websupport=1.0.1=py36hb5e5916_1
  - spyder=3.3.6=py36_0
  - spyder-kernels=0.5.1=py36_0
  - sqlalchemy=1.2.7=py36ha85dd04_0
  - sqlite=3.28.0=he774522_0
  - statsmodels=0.9.0=py36h452e1ab_0
  - sympy=1.1.1=py36h96708e0_0
  - tbb=2019.1=h74a9793_0
  - tblib=1.3.2=py36h30f5020_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.9.0=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h096827d_0
  - traits=4.6.0=py36hfa6e2cd_3
  - traitsui=6.0.0=py36_1
  - typing=3.6.4=py36_0
  - unicodecsv=0.14.1=py36h6450c06_0
  - urllib3=1.22=py36h276f60a_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - vtk=8.1.1=py36h1e53df8_204
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36h67c50ae_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - win_inet_pton=1.0.1=py36he67d7fd_1
  - win_unicode_console=0.5=py36hcdbd4b5_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - wrapt=1.10.11=py36he5f5981_0
  - xlrd=1.1.0=py36h1cb58dc_1
  - xlsxwriter=1.0.4=py36_0
  - xlwings=0.11.8=py36_0
  - xlwt=1.3.0=py36h1a4751e_0
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=hc6251cf_0
  - zict=0.1.3=py36h2d8e73e_0
  - zlib=1.2.11=h8395fce_2
prefix: C:\Users\User\Anaconda3\envs\rc
